### ISSUE TITLE
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/nbconvert-feedstock#27]
Creating an env with `jupyter_contrib_nbextensions` triggers a tornado error in `nbconvert`. `nbconvert` does not depended on tornado directly so I'm not sure what package is pulling the bad version.

 
```
> conda create --name TEST python=3.7 jupyter ipykernel jupyter_contrib_nbextensions
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/filipe/miniconda3/envs/TEST

  added / updated specs:
    - ipykernel
    - jupyter
    - jupyter_contrib_nbextensions
    - python=3.7


The following NEW packages will be INSTALLED:

  atk                conda-forge/linux-64::atk-2.25.90-hb9dd440_1002
  attrs              conda-forge/noarch::attrs-19.1.0-py_0
  backcall           conda-forge/noarch::backcall-0.1.0-py_0
  bleach             conda-forge/noarch::bleach-3.1.0-py_0
  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  ca-certificates    conda-forge/linux-64::ca-certificates-2018.11.29-ha4d7672_0
  cairo              conda-forge/linux-64::cairo-1.16.0-ha4e643d_1000
  certifi            conda-forge/linux-64::certifi-2018.11.29-py37_1000
  dbus               conda-forge/linux-64::dbus-1.13.0-h4e0c4b3_1000
  decorator          conda-forge/noarch::decorator-4.3.2-py_0
  entrypoints        conda-forge/linux-64::entrypoints-0.3-py37_1000
  expat              conda-forge/linux-64::expat-2.2.5-hf484d3e_1002
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h2176d3f_1000
  freetype           conda-forge/linux-64::freetype-2.9.1-h94bbf69_1005
  gdk-pixbuf         conda-forge/linux-64::gdk-pixbuf-2.36.12-h49783d7_1002
  gettext            conda-forge/linux-64::gettext-0.19.8.1-h9745a5d_1001
  glib               conda-forge/linux-64::glib-2.58.3-hf63aee3_1001
  gobject-introspec~ conda-forge/linux-64::gobject-introspection-1.58.2-py37h2da5eee_1000
  graphite2          conda-forge/linux-64::graphite2-1.3.13-hf484d3e_1000
  gstreamer          conda-forge/linux-64::gstreamer-1.14.4-h66beb1c_1001
  gtk2               conda-forge/linux-64::gtk2-2.24.31-hb68c50a_1001
  harfbuzz           conda-forge/linux-64::harfbuzz-2.3.1-h6824563_0
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  ipykernel          conda-forge/linux-64::ipykernel-5.1.0-py37h24bf2e0_1002
  ipython            conda-forge/linux-64::ipython-7.3.0-py37h24bf2e0_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  ipywidgets         conda-forge/noarch::ipywidgets-7.4.2-py_0
  jedi               conda-forge/linux-64::jedi-0.13.3-py37_0
  jinja2             conda-forge/noarch::jinja2-2.10-py_1
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  jsonschema         conda-forge/linux-64::jsonschema-3.0.1-py37_0
  jupyter            conda-forge/noarch::jupyter-1.0.0-py_1
  jupyter_client     conda-forge/noarch::jupyter_client-5.2.4-py_3
  jupyter_console    conda-forge/noarch::jupyter_console-6.0.0-py_0
  jupyter_contrib_c~ conda-forge/noarch::jupyter_contrib_core-0.3.3-py_2
  jupyter_contrib_n~ conda-forge/linux-64::jupyter_contrib_nbextensions-0.5.1-py37_0
  jupyter_core       conda-forge/noarch::jupyter_core-4.4.0-py_0
  jupyter_highlight~ conda-forge/linux-64::jupyter_highlight_selected_word-0.2.0-py37_1000
  jupyter_latex_envs conda-forge/linux-64::jupyter_latex_envs-1.4.4-py37_1000
  jupyter_nbextensi~ conda-forge/linux-64::jupyter_nbextensions_configurator-0.4.1-py37_0
  libffi             conda-forge/linux-64::libffi-3.2.1-hf484d3e_1005
  libgcc-ng          conda-forge/linux-64::libgcc-ng-7.3.0-hdf63c60_0
  libiconv           conda-forge/linux-64::libiconv-1.15-h14c3975_1004
  libpng             conda-forge/linux-64::libpng-1.6.36-h84994c4_1000
  libsodium          conda-forge/linux-64::libsodium-1.0.16-h14c3975_1001
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-7.3.0-hdf63c60_0
  libtiff            conda-forge/linux-64::libtiff-4.0.10-h9022e91_1002
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.8-h143f9aa_1005
  libxslt            conda-forge/linux-64::libxslt-1.1.32-h4785a14_1002
  lxml               conda-forge/linux-64::lxml-4.3.2-py37h23eabaa_0
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py37h14c3975_0
  mistune            conda-forge/linux-64::mistune-0.8.4-py37h14c3975_1000
  nbconvert          conda-forge/noarch::nbconvert-5.3.1-py_1
  nbformat           conda-forge/noarch::nbformat-4.4.0-py_1
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  notebook           conda-forge/linux-64::notebook-5.7.5-py37_0
  openssl            conda-forge/linux-64::openssl-1.0.2r-h14c3975_0
  pandoc             conda-forge/linux-64::pandoc-2.6-1
  pandocfilters      conda-forge/noarch::pandocfilters-1.4.2-py_1
  pango              conda-forge/linux-64::pango-1.40.14-h4ea9474_1004
  parso              conda-forge/noarch::parso-0.3.4-py_0
  pcre               conda-forge/linux-64::pcre-8.41-hf484d3e_1003
  pexpect            conda-forge/linux-64::pexpect-4.6.0-py37_1000
  pickleshare        conda-forge/linux-64::pickleshare-0.7.5-py37_1000
  pip                conda-forge/linux-64::pip-19.0.3-py37_0
  pixman             conda-forge/linux-64::pixman-0.34.0-h14c3975_1003
  prometheus_client  conda-forge/noarch::prometheus_client-0.6.0-py_0
  prompt_toolkit     conda-forge/noarch::prompt_toolkit-2.0.9-py_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  ptyprocess         conda-forge/linux-64::ptyprocess-0.6.0-py37_1000
  pygments           conda-forge/noarch::pygments-2.3.1-py_0
  pyqt               conda-forge/linux-64::pyqt-5.6.0-py37h13b7fb3_1008
  pyrsistent         conda-forge/linux-64::pyrsistent-0.14.11-py37h14c3975_0
  python             conda-forge/linux-64::python-3.7.1-hd21baee_1001
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  pyyaml             conda-forge/linux-64::pyyaml-3.13-py37h14c3975_1001
  pyzmq              conda-forge/linux-64::pyzmq-18.0.1-py37h0e1adb2_0
  qt                 conda-forge/linux-64::qt-5.6.2-hce4f676_1013
  qtconsole          conda-forge/noarch::qtconsole-4.4.3-py_0
  readline           conda-forge/linux-64::readline-7.0-hf8c457e_1001
  send2trash         conda-forge/noarch::send2trash-1.5.0-py_0
  setuptools         conda-forge/linux-64::setuptools-40.8.0-py37_0
  sip                conda-forge/linux-64::sip-4.18.1-py37hf484d3e_1000
  six                conda-forge/linux-64::six-1.12.0-py37_1000
  sqlite             conda-forge/linux-64::sqlite-3.26.0-h67949de_1000
  terminado          conda-forge/linux-64::terminado-0.8.1-py37_1001
  testpath           conda-forge/linux-64::testpath-0.4.2-py37_1000
  tk                 conda-forge/linux-64::tk-8.6.9-h84994c4_1000
  tornado            conda-forge/linux-64::tornado-6.0.1-py37h14c3975_0
  traitlets          conda-forge/linux-64::traitlets-4.3.2-py37_1000
  wcwidth            conda-forge/noarch::wcwidth-0.1.7-py_1
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  wheel              conda-forge/linux-64::wheel-0.33.1-py37_0
  widgetsnbextension conda-forge/linux-64::widgetsnbextension-3.4.2-py37_1000
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.9-h14c3975_1004
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h4937e3b_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.7-h14c3975_1000
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.2-h14c3975_1007
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.3-h14c3975_1004
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h14c3975_1002
  xorg-libxt         conda-forge/linux-64::xorg-libxt-1.1.5-h14c3975_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  yaml               conda-forge/linux-64::yaml-0.1.7-h14c3975_1001
  zeromq             conda-forge/linux-64::zeromq-4.2.5-hf484d3e_1006
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004
  zstd               conda-forge/linux-64::zstd-1.3.3-1


Proceed ([y]/n)? y

Preparing transaction: done
Executing transaction: - Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

/ ++ /home/filipe/miniconda3/envs/TEST/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''jupyter_highlight_selected_word'\'', sys_prefix=True, logger=logging.getLogger())'

| ++ /home/filipe/miniconda3/envs/TEST/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''latex_envs'\'', sys_prefix=True, logger=logging.getLogger())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/latex_envs/__init__.py", line 3, in <module>
    from . import latex_envs
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/latex_envs/latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/__init__.py", line 7, in <module>
    from . import postprocessors
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
    from .serve import ServePostProcessor
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
    class ProxyHandler(web.RequestHandler):
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'conda-forge::jupyter_latex_envs-1.4.4-py37_1000'.
LinkError: post-link script failed for package conda-forge::jupyter_latex_envs-1.4.4-py37_1000
running your command again with `-v` will provide additional information
location of failed script: /home/filipe/miniconda3/envs/TEST/bin/.jupyter_latex_envs-post-link.sh
==> script messages <==
++ /home/filipe/miniconda3/envs/TEST/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''latex_envs'\'', sys_prefix=True, logger=logging.getLogger())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/latex_envs/__init__.py", line 3, in <module>
    from . import latex_envs
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/latex_envs/latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/__init__.py", line 7, in <module>
    from . import postprocessors
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
    from .serve import ServePostProcessor
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
    class ProxyHandler(web.RequestHandler):
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'


Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::jupyter_latex_envs-1.4.4-py37_1000
running your command again with `-v` will provide additional information
location of failed script: /home/filipe/miniconda3/envs/TEST/bin/.jupyter_latex_envs-post-link.sh
==> script messages <==
++ /home/filipe/miniconda3/envs/TEST/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''latex_envs'\'', sys_prefix=True, logger=logging.getLogger())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/latex_envs/__init__.py", line 3, in <module>
    from . import latex_envs
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/latex_envs/latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/__init__.py", line 7, in <module>
    from . import postprocessors
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
    from .serve import ServePostProcessor
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
    class ProxyHandler(web.RequestHandler):
  File "/home/filipe/miniconda3/envs/TEST/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```

Ping @minrk

**Comment by ocefpaf** [comment]
Looks like the problem is a package with bad metadata somewhere that is forcing a downgrade for `nbconvert`. @minrk I checked and by removing `nbconvert-5.3.1` we can get the "right" package solution. Are you OK marking `nbconvert-5.3.1` that package as broken?

**Comment by minrk** [comment]
It looks like it's the pin-down of pandoc that's causing the issue, causing the solver to prefer (pandoc 2, nbconvert 5.3) over (pandoc 1, nbconvert 5.4). I'm not sure if marking 5.3.1 as broken will fix it, since it will probably just prefer the next release older than that, unless we mark *all* old nbconverts as broken. Is hotfixing past nbconverts to have `pandoc<2` an option?

**Comment by minrk** [comment]
I think it only fixed it for Python 3.7 because 5.3.1 was the only other install candidate for py37.  When I create an env with python=3.6, I get nbconvert 5.3.0, the last release before we started noarch builds.

I opened https://github.com/jupyter/nbconvert/pull/964 to unpin pandoc 2 and it turns out to be an over-cautious warning, and pandoc 2 actually works just fine. So we could remove the pinning from 

So I think the options are

1. unpin pandoc <2 and live with the warning until the next nbconvert release (#28)
2. hotfix all past nbconverts<5.4.1 to pin pandoc <2
3. same as 1. but patch out pandoc<2 warning
4. wait for next nbconvert release, which should fix pandoc 2 issues (just warnings as far as I can tell)

**Comment by ocefpaf** [comment]
> I think it only fixed it for Python 3.7 because 5.3.1 was the only other install candidate for py37. When I create an env with python=3.6, I get nbconvert 5.3.0, the last release before we started noarch builds.

Yep.

> I opened [jupyter/nbconvert#964](https://github.com/jupyter/nbconvert/pull/964) to unpin pandoc 2 and it turns out to be an over-cautious warning, and pandoc 2 actually works just fine. So we could remove the pinning from

:+1: 

> So I think the options are
> 
> 1. unpin pandoc <2 and live with the warning until the next nbconvert release (#28)
> 2. hotfix all past nbconverts<5.4.1 to pin pandoc <2
> 3. same as 1. but patch out pandoc<2 warning
> 4. wait for next nbconvert release, which should fix pandoc 2 issues (just warnings as far as I can tell)

I'm fine with #28, probably the best/easiest option here.

**Comment by minrk** [comment]
Let's go with that, then. Then it's a hopefully minor annoyance that folks will get a warning about pandoc 2 until the next nbconvert is released with the fix.

**Comment by lwasser** [comment]
hey there @ocefpaf and @minrk please tell me if i'm in the wrong place but i just have been getting a similar error

```
urllib3-1.24.3       | 151 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... Uninstalling jupyter-js-widgets jupyter-js-widgets/extension
Removing: /opt/conda/share/jupyter/nbextensions/jupyter-js-widgets

Enabling nb_conda_kernels...
Status: enabled

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

++ /opt/conda/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''jupyter_highlight_selected_word'\'', sys_prefix=True, logger=logging.getLogger())'

++ /opt/conda/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''latex_envs'\'', sys_prefix=True, logger=logging.getLogger())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/opt/conda/lib/python3.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/opt/conda/lib/python3.7/site-packages/latex_envs/__init__.py", line 3, in <module>
    from . import latex_envs
  File "/opt/conda/lib/python3.7/site-packages/latex_envs/latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/__init__.py", line 7, in <module>
    from . import postprocessors
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
    from .serve import ServePostProcessor
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
    class ProxyHandler(web.RequestHandler):
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'conda-forge::jupyter_latex_envs-1.4.4-py37_1000'.
LinkError: post-link script failed for package conda-forge::jupyter_latex_envs-1.4.4-py37_1000
running your command again with `-v` will provide additional information
location of failed script: /opt/conda/bin/.jupyter_latex_envs-post-link.sh
==> script messages <==
++ /opt/conda/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''latex_envs'\'', sys_prefix=True, logger=logging.getLogger())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/opt/conda/lib/python3.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/opt/conda/lib/python3.7/site-packages/latex_envs/__init__.py", line 3, in <module>
    from . import latex_envs
  File "/opt/conda/lib/python3.7/site-packages/latex_envs/latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/__init__.py", line 7, in <module>
    from . import postprocessors
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
    from .serve import ServePostProcessor
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
    class ProxyHandler(web.RequestHandler):
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'


Attempting to roll back.

Rolling back transaction: ...working... done

LinkError: post-link script failed for package conda-forge::jupyter_latex_envs-1.4.4-py37_1000
running your command again with `-v` will provide additional information
location of failed script: /opt/conda/bin/.jupyter_latex_envs-post-link.sh
==> script messages <==
++ /opt/conda/bin/python -c 'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import install_nbextension_python; install_nbextension_python('\''latex_envs'\'', sys_prefix=True, logger=logging.getLogger())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/opt/conda/lib/python3.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/opt/conda/lib/python3.7/site-packages/latex_envs/__init__.py", line 3, in <module>
    from . import latex_envs
  File "/opt/conda/lib/python3.7/site-packages/latex_envs/latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/__init__.py", line 7, in <module>
    from . import postprocessors
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
    from .serve import ServePostProcessor
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
    class ProxyHandler(web.RequestHandler):
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```

Git repo:
https://github.com/earthlab/earth-analytics-python-env/pull/46

Docker build: https://cloud.docker.com/u/earthlab/repository/docker/earthlab/earth-analytics-python-env 

If you have any suggestions regarding a fix i'd be greatly appreciative. if you'd like this comment elsewhere please say the word as well! Many thanks

**Comment by lwasser** [comment]
actually docker just ran successfully for some reason yet i have this issue locally. please hold on any action until i sort this out on my end. my apologies. i've had a slew of conda channel issues today that i think were related to users not updated their conda forge feedstocks?

**Comment by ocefpaf** [comment]
> actually docker just ran successfully for some reason yet i have this issue locally.

@lwasser in the world of packaging it is complicated to comment on a closed issue b/c the symptoms can be similar but your issue may be completely different. We also have some boilerplate debug info we need people to fill in order to be able to debug it.

With that said this issue was resolved a while ago and you may just need an update.


> please hold on any action until i sort this out on my end. my apologies. i've had a slew of conda channel issues today that i think were related to users not updated their conda forge feedstocks?

If you know about any feedstock that has stale packages please open issues on them and ping me and I can work with the feedstock maintainers to fix/update them.

**Comment by lwasser** [comment]
Ok no worries. i'll open an issue about the dated feedstocks as a starting point and will also look into update. Thank you @ocefpaf  In the future i i'll avoid commenting on closed issues! I appreciate the speedy feedback.

**Comment by ocefpaf** [comment]
> I'll avoid commenting on closed issues!

Commenting on closed issue is perfect valid in many cases but it can confusing with packaging b/c the errors are may look the same but the problems are usually different. We (conda-forge) are discussing locking the issues to force people to always open new ones.
