### ISSUE TITLE
Update to nbconvert package requirements

### ISSUE THREAD

**Issue by aphearin** [conda-forge/nbconvert-feedstock#81]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I cannot launch a jupyter notebook after creating a new minimal environment with conda-forge as my primary channel. I think the issue may be to do with the dependency chain of nbconvert.

```
$ conda create -n py39 python=3.9 numpy matplotlib ipython jupyter
$ conda activate py39
$ jupyter notebook

[I 12:24:36.004 NotebookApp] Creating new notebook in 
[E 12:24:36.112 NotebookApp] Uncaught exception GET /notebooks/Untitled3.ipynb?kernel_name=python3 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled3.ipynb?kernel_name=python3', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tornado/gen.py", line 782, in run
        yielded = self.gen.send(value)
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/notebook/notebook/handlers.py", line 94, in get
        self.write(self.render_template('notebook.html',
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/notebook/base/handlers.py", line 511, in render_template
        return template.render(**ns)
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
        self.environment.handle_exception()
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/notebook/templates/notebook.html", line 115, in block 'header'
        {% for exporter in get_frontend_exporters() %}
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
        from .html import HTMLExporter
      File "/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/nbconvert/exporters/html.py", line 12, in <module>
        from jinja2 import contextfilter
    ImportError: cannot import name 'contextfilter' from 'jinja2' (/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/jinja2/__init__.py)
[E 12:24:36.118 NotebookApp] {
      "Host": "localhost:8888",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Referer": "http://localhost:8888/tree",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
    }
[E 12:24:36.118 NotebookApp] 500 GET /notebooks/Untitled3.ipynb?kernel_name=python3 (::1) 50.470000ms referer=http://localhost:8888/tree

```

The reason I think the issue may be to do with nbconvert is that this traceback:
```
 ImportError: cannot import name 'contextfilter' from 'jinja2'
```

After launching ipython, I can successfully import `jinja2`, but not `nbconvert`:
```
In [1]: import jinja2

In [2]: import nbconvert
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In [2], line 1
----> 1 import nbconvert

File ~/opt/miniconda3/envs/py39/lib/python3.9/site-packages/nbconvert/__init__.py:4
      1 """Utilities for converting notebooks to and from different formats."""
      3 from ._version import version_info, __version__
----> 4 from .exporters import *
      5 from . import filters
      6 from . import preprocessors

File ~/opt/miniconda3/envs/py39/lib/python3.9/site-packages/nbconvert/exporters/__init__.py:3
      1 from .base import (export, get_exporter, 
      2                    ExporterNameError, get_export_names)
----> 3 from .html import HTMLExporter
      4 from .slides import SlidesExporter
      5 from .templateexporter import TemplateExporter

File ~/opt/miniconda3/envs/py39/lib/python3.9/site-packages/nbconvert/exporters/html.py:12
     10 from traitlets.config import Config
     11 from jupyter_core.paths import jupyter_path
---> 12 from jinja2 import contextfilter
     14 from nbconvert.filters.highlight import Highlight2HTML
     15 from nbconvert.filters.markdown_mistune import IPythonRenderer, MarkdownWithMath

ImportError: cannot import name 'contextfilter' from 'jinja2' (/Users/aphearin/opt/miniconda3/envs/py39/lib/python3.9/site-packages/jinja2/__init__.py)

```

### Installed packages

```shell
(py39) aphearin 0927 $ conda list
# packages in environment at /Users/aphearin/opt/miniconda3/envs/py39:
#
# Name                    Version                   Build  Channel
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39h63b48b0_2    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h5eb16cf_7    conda-forge
brotli-bin                1.0.9                h5eb16cf_7    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2022.9.24            h033912b_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39hae9ecf2_0    conda-forge
contourpy                 1.0.5            py39h92daf61_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h811a1a6_3    conda-forge
debugpy                   1.6.3            py39hd91caee_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.4.9                hf0c8a7f_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.37.3           py39ha30fb19_0    conda-forge
freetype                  2.12.1               h3f81eb7_0    conda-forge
gettext                   0.19.8.1          h8a4c099_1009    conda-forge
icu                       68.2                 he49afe7_0    conda-forge
importlib-metadata        4.11.4           py39h6e9494a_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.16.0             pyh736e0ef_0    conda-forge
ipython                   8.5.0              pyhd1c38e8_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                8.0.2              pyhd8ed1ab_1    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jpeg                      9e                   hac89ed1_2    conda-forge
jsonschema                4.16.0             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py39h6e9494a_7    conda-forge
jupyter_client            7.3.5              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py39h6e9494a_0    conda-forge
jupyterlab_widgets        3.0.3              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4            py39h7c694c3_0    conda-forge
krb5                      1.19.3               hb98e516_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libblas                   3.9.0           16_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eb16cf_7    conda-forge
libbrotlidec              1.0.9                h5eb16cf_7    conda-forge
libbrotlienc              1.0.9                h5eb16cf_7    conda-forge
libcblas                  3.9.0           16_osx64_openblas    conda-forge
libclang                  11.1.0          default_he082bbe_1    conda-forge
libcxx                    14.0.6               hccf4f1f_0    conda-forge
libdeflate                1.14                 hb7f2c08_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           10_4_0_h97931a8_25    conda-forge
libgfortran5              11.3.0              h082f757_25    conda-forge
libglib                   2.72.1               hfbcb929_0    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
liblapack                 3.9.0           16_osx64_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_3    conda-forge
libopenblas               0.3.21          openmp_h429af6e_3    conda-forge
libpng                    1.6.38               ha978bb4_0    conda-forge
libpq                     13.5                 h8ce7ee7_1    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsqlite                 3.39.3               ha978bb4_0    conda-forge
libtiff                   4.4.0                hdb44e8a_4    conda-forge
libwebp-base              1.2.4                h775f41a_0    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libzlib                   1.2.12               hfd90126_3    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
markupsafe                2.1.1            py39h63b48b0_1    conda-forge
matplotlib                3.6.0            py39h6e9494a_0    conda-forge
matplotlib-base           3.6.0            py39hb2f573b_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py39h89e85a6_1005    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.30               hc4b2c72_1    conda-forge
mysql-libs                8.0.30               h8658499_1    conda-forge
nbconvert                 5.6.1              pyhd8ed1ab_2    conda-forge
nbformat                  5.6.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
nspr                      4.32                 hcd9eead_1    conda-forge
nss                       3.78                 ha8197d3_0    conda-forge
numpy                     1.23.3           py39h34843a6_0    conda-forge
openjpeg                  2.5.0                h5d0d7b0_1    conda-forge
openssl                   3.0.5                hfd90126_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py39h4d560c1_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
prompt_toolkit            3.0.31               hd8ed1ab_0    conda-forge
psutil                    5.9.2            py39ha30fb19_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39h9d385e7_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.18.1           py39h63b48b0_1    conda-forge
python                    3.9.13          hf8d34f4_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pyzmq                     24.0.1           py39hed8f129_0    conda-forge
qt                        5.12.9               h126340a_4    conda-forge
qtconsole                 5.3.2              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.2              pyha770c72_0    conda-forge
qtpy                      2.2.0              pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                65.4.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.39.3               h9ae0607_0    conda-forge
stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
terminado                 0.15.0           py39h6e9494a_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   6.2              py39h701faf5_0    conda-forge
traitlets                 5.4.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022d                h191b570_0    conda-forge
unicodedata2              14.0.0           py39h63b48b0_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.3              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               hfd90126_3    conda-forge
zstd                      1.5.2                hfa58983_4    conda-forge
```

### Environment info

```shell
(py39) aphearin 0927 $ conda info

     active environment : py39
    active env location : /Users/aphearin/opt/miniconda3/envs/py39
            shell level : 3
       user config file : /Users/aphearin/.condarc
 populated config files : /Users/aphearin/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.7.12.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/aphearin/opt/miniconda3  (writable)
      conda av data dir : /Users/aphearin/opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/aphearin/opt/miniconda3/pkgs
                          /Users/aphearin/.conda/pkgs
       envs directories : /Users/aphearin/opt/miniconda3/envs
                          /Users/aphearin/.conda/envs
               platform : osx-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.7.12 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by aphearin** [comment]
Googling around, it looks like this issue has been encountered by others [here](https://github.com/d2l-ai/d2l-book/issues/46). And both [here](https://discourse.jupyter.org/t/500-internal-server-error-jinja2-related/13878) and [here](https://stackoverflow.com/questions/73139964/running-reprexpy-on-pycharm-ce-importerror-cannot-import-name-contextfilter), people seem to have resolved the issue by upgrading `nbcovert`.

**Comment by bollwyvl** [comment]
Yes, the version of `nbconvert` you are pulling with that solve is quite old. It's probably _technically_ accurate, given the data at the time, but doesn't take into account some of the future things that happened after its release, namely a series of breaking changes in `jinja2` which caused _many_ projects to break for a few weeks.

A couple of those deps (`jupyter`, `matplotlib`) bring a _lot_ of baggage, such as `qt`: sometimes those hard-to-solve binary dependencies can "overpower" the desire for newer packages, leading to an undesirable local maximum for other packages.

An apparently-functional solve (can't test, no fruit box) might be:

```bash
CONDA_PREFIX=osx-64 conda create -n py39 python=3.9 matplotlib-base notebook ipywidgets
```

This pulls much more modern versions, namely:

```
ipykernel          conda-forge/noarch::ipykernel-6.16.0-pyh736e0ef_0
ipython            conda-forge/noarch::ipython-8.5.0-pyhd1c38e8_1
jinja2             conda-forge/noarch::jinja2-3.1.2-pyhd8ed1ab_1
matplotlib-base    conda-forge/osx-64::matplotlib-base-3.6.0-py39hb2f573b_0
nbconvert          conda-forge/noarch::nbconvert-7.0.0-pyhd8ed1ab_0
notebook           conda-forge/noarch::notebook-6.4.12-pyha770c72_0
```

The next few months may well see a number of additional changes (e.g. `notebook=7`): it's likely worthwhile to figure out what are good packages for your  currently workflow, and check them in as an `environment.yml` with suitable minimum and maximum bounds for tools you care about.

You can go further and use tools like https://github.com/conda-incubator/conda-lock to get even more-reproducible solves.

**Comment by beckermr** [comment]
conda-forge has a strong tradition of making things just work. Whatever dependency changes that are needed here need to be submitted as repodata patches. There’s no good reason a user should have to google around for basic functionality to work after a standard environment creation step. Suggesting that users figure out the correct dependencies locally and pin them on their system defeats the point of using a system like conda in the first place. 

What are the incorrect constraints?

**Comment by beckermr** [comment]
We likely need to patch old nbconvert versions with a jinja2 upper limit.

**Comment by bollwyvl** [comment]
>  patch old nbconvert versions

looking at that [specific version](https://github.com/conda-forge/nbconvert-feedstock/pull/33/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aL23), at _least_ `jinja2<3.1` and `mistune>=0.8.1,<1`... but probably more. These were intentionally left underspecified upstream, so it can be a bit challenging to dig up when some of the key supported versions changed.

the larger issue (of `conda` picking very old versions to avoid constraints) has come up in a lot of places. In this specific case, `mamb` does the "correct" thing, bringing in `nbconvert 7`

**Comment by bollwyvl** [comment]
This looks like one of the key PRs, which adds some version detection logic:

- https://github.com/jupyter/nbconvert/pull/1624

**Comment by beckermr** [comment]
I'll make a pr later

**Comment by beckermr** [comment]
Feel free to reopen @aphearin if the patch I put in above doesn't work on a new env tomorrow.

**Comment by beckermr** [comment]
I tested this and it is now fixed.

**Comment by aphearin** [comment]
Thanks @beckermr and @bollwyvl for fixing this so quickly!
